server:
  port: 9099

management:
  server:
    port: 10099

logging:
  level:
    com.baloise.open.strava.edw.infrastructure.web: DEBUG

strava:
  auth:
    redirect-url: "http://localhost:${server.port}/strava/auth"
